spring:
  application:
    name: buyornot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:3306/buyornot
    username: ambiguous
    password: ambiguous

server:
  servlet:
    encoding:
      force: true